FROM node:22.8.0-slim

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon

# debian 
# RUN useradd -u 1000 -m userxpto
# RUN usermod -u 1000 userxpto

# alpine
# RUN adduser -D -u 1000 userxpto
# RUN sed -i 's/1000/10001/g' /etc/passwd

USER node

WORKDIR /home/node/app

COPY package.json ./
RUN npm install