FROM node:22.8.0-slim

ARG NODEMON_VERSION=3.1.7

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon@$NODEMON_VERSION

# debian 
# RUN useradd -u 1000 -m userxpto
# RUN usermod -u 1000 userxpto

# alpine
# RUN adduser -D -u 1000 userxpto
# RUN sed -i 's/1000/10001/g' /etc/passwd
COPY start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app

# COPY package.json ./
# RUN npm install

EXPOSE 3000

# CMD ["tail", "-f", "/dev/null"]
# CMD ["/home/node/app/start.sh"]
 
CMD ["node", "-v"]