include:
  - ./external-api/docker-compose.external-api.yaml

services:
  web1:
    extends:
      file: docker-compose.common.yaml
      service: web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  web2:
    extends:
      file: docker-compose.common.yaml
      service: web
    profiles: [nginx]
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_base
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  nginx:
    build: ./.docker/nginx
    restart: always
    profiles: [nginx]
    ports:
      - "4000:80"
    # volumes:
    #   - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    develop:
      watch:
        - action: sync+restart
          x-initialSync: true
          path: ./.docker/nginx/nginx.conf
          target: /etc/nginx/nginx.conf
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    profiles: [debug]
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy